name: Astro Testing Auto-Deploy

env:
  deployToRepo: astro-testing

on:
  # Triggers the workflow on push and pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # GitHub!!!!
      - name: Checkout builds
        uses: actions/checkout@master
        with:
          ref: "public"
          path: "public"

      # Install dependencies with pnpm
      - name: Install dependencies
        run: npm ci

      # Build the project and add .nojekyll file to supress default behaviour
      - name: Build
        run: |
          npm run build
          touch ./dist/.nojekyll

      # - name: Push builds
      #   run: |
      #     cd $GITHUB_WORKSPACE/public
      #     git config --local user.email "actions@github.com"
      #     git config --local user.name "GitHub Actions"
      #     git add .
      #     git commit -m "Build $GITHUB_SHA" || true   # do not error if nothing to commit
      #     git push

      # Push to your pages repo
      - name: Push to pages repo
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          folder: 'dist'
          branch: gh-pages
          git-config-name: GitHub Actions
          git-config-email: actions@github.com"
          commit-message: Deploy ORIGIN_COMMIT

      # Push to your pages repo
      # - name: Push to pages repo
      #   uses: cpina/github-action-push-to-another-repository@main
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      #   with:
      #     source-directory: 'dist'
      #     destination-github-username: ${{ github.actor }}
      #     destination-repository-name: ${{ env.deployToRepo }}
      #     user-email: ${{ env.githubEmail }}
      #     commit-message: Deploy ORIGIN_COMMIT
      #     target-branch: gh-pages